#! /usr/bin/bash

source /home/pi/venv/vgc/bin/activate
export PYTHONPATH=/home/pi/growcontrol

echo "server | tst | http | watchdog | kill"
echo "$1"

if [[ "$1" == "server" ]]; then
    python servers/sensors_server.py &
    python servers/actors_server.py &
    sleep 2
    python servers/logdata_server.py &
fi

if [[ "$1" == "tst" ]]; then
    python client/tst_client.py
fi 

if [[ "$1" == "http" ]]; then
    cd http && flask --app http_server run --debug --host 0.0.0.0
fi

if [[ "$1" == "watchdog" ]]; then 
    python watchdog.py 
fi

if [[ "$1" == "kill" ]]; then 
    pkill python 
    pkill flask
fi

