#! /usr/bin/bash

source /home/pi/venv/vgc/bin/activate
export PYTHONPATH=/home/pi/growcontrol

echo "server | tst | http | watchdog"
echo "$1"

if [[ "$1" == "server" ]]; then
    python servers/sensors_server.py &
    python servers/light_server.py &
    sleep 2
    python servers/fan_server.py &
    python servers/pump_server.py 1 &
    # python servers/pump_server.py 2 &
    python servers/logdata_server.py &
fi

if [[ "$1" == "tst" ]]; then
    python client/tst_client.py
fi 

if [[ "$1" == "http" ]]; then
    cd http && flask --app http_server run --debug --host 0.0.0.0
fi

echo P1
if [[ "$1" == "watchdog" ]]; then 
    echo P2 $1 
    python watchdog.py 
fi
echo P3