#! /usr/bin/bash
# this script should be sourced
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
_PATH=$SCRIPT_DIR/../..
export PYTHONPATH=${_PATH}:${_PATH}/mock
python ${_PATH}/servers/sensors_server.py &
python ${_PATH}/servers/fan_server.py &
python mock_server.py &
sleep 2
echo "done"
echo "to kill:"
echo "$_PATH/test/terminate"
